version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    container_name: budget-io-postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
